export PATH="$HOME/bin:$HOME/.local/bin:$PATH"

# Snap
export PATH=$PATH:/snap/bin

# Go
export PATH="$(go env GOPATH)/bin:$PATH"

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

# nvm
export NVM_DIR="$HOME/.nvm"

