---
- name: Install zsh
  become: yes
  ansible.builtin.apt:
    name:
      - zsh
- name: Install zplug
  git:
    repo: https://github.com/zplug/zplug
    dest: "{{ ansible_env.HOME }}/.zplug"
- name: Initialize zplug
  shell: source "{{ ansible_env.HOME }}/.zplug/init.zsh"
  args:
    executable: /bin/zsh
