format = """
$directory\
$git_branch\
$git_status\
$character\
"""

right_format = """
$golang\
$python\
$nodejs\
$terraform\
"""

add_newline = false

palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[directory]
style = "bold lavender"
format = "[$path ]($style)"

[git_branch]
symbol = " "
format = "[$symbol$branch ]($style)"
style = "bold maroon"

[git_status]
style = "bold maroon"
ahead = "+"
behind = "-"
stashed = ""
modified = "M"
staged = "S"
renamed = "R"
deleted = "D"
typechanged = "T"

[character]
success_symbol = "[](green)"
error_symbol = "[](red)"
vimcmd_symbol = "[](blue)"

[nodejs]
format = "[$symbol($version )]($style)"
style = "bold green"

[python]
symbol = "󰌠 "
format = "[$symbol($version )]($style)"
style = "bold yellow"

[golang]
symbol = "󰟓 "
format = "[$symbol($version )]($style)"
style = "bold sky"

[terraform]
symbol = "󱁢 "
format = "[$symbol$workspace ]($style)"
style = "bold lavender"

[kubernetes]
disabled = false
symbol = "󱃾 "
format = "[$symbol$context(/$namespace)]($style)"
style = "bold blue"
