"""Generate Codex config while retaining live settings outside migration ownership."""
import copy
import datetime
import json
import math
import os
from pathlib import Path
import sys
import tempfile
import tomllib


class PreflightError(ValueError):
    """A safe diagnostic containing paths, never configuration contents."""


def merge(defaults, current):
    result = copy.deepcopy(defaults)
    for key, value in current.items():
        result[key] = merge(result[key], value) if isinstance(value, dict) and isinstance(result.get(key), dict) else copy.deepcopy(value)
    return result


def scalar(value):
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, bool):
        return str(value).lower()
    if isinstance(value, (datetime.datetime, datetime.date, datetime.time)):
        return value.isoformat()
    if isinstance(value, float) and not math.isfinite(value):
        return 'nan' if math.isnan(value) else ('inf' if value > 0 else '-inf')
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, list):
        return '[' + ', '.join(scalar(item) for item in value) + ']'
    if isinstance(value, dict):
        return '{' + ', '.join(json.dumps(key) + ' = ' + scalar(item) for key, item in value.items()) + '}'
    raise ValueError('unsupported TOML value')


def serialize(data):
    lines = ['# Generated by codex-sync; unrelated live settings are preserved.']
    def table(values, path):
        if path:
            lines.extend(['', '[' + '.'.join(json.dumps(key) for key in path) + ']'])
        for key, value in values.items():
            if not isinstance(value, dict):
                lines.append(json.dumps(key) + ' = ' + scalar(value))
        for key, value in values.items():
            if isinstance(value, dict):
                table(value, path + [key])
    table(data, [])
    text = '\n'.join(lines) + '\n'
    if tomllib.loads(text) != data:
        raise ValueError('TOML serialization failed semantic verification')
    return text


def read(path):
    if path.is_symlink() and not path.exists():
        raise PreflightError(f'dangling config symlink: {path}')
    return tomllib.loads(path.read_text()) if path.exists() else {}


def main():
    root = Path(sys.argv[1]).resolve()
    home = Path(os.environ['HOME'])
    codex = Path(os.environ.get('CODEX_HOME', str(home / '.codex')))
    directory = root / 'codex/.codex'
    generated = directory / 'config.toml'
    live = codex / 'config.toml'
    activate = 'CODEX_HOME' in os.environ or os.environ.get('CODEX_SYNC_LIVE') == '1' or root == (home / 'workspace/dotfiles').resolve()
    if generated.is_symlink() or (generated.exists() and not generated.is_file()):
        raise PreflightError(f'generated destination must be a regular file: {generated}')
    if not activate and live.resolve() == generated.resolve():
        raise PreflightError('generation would modify live config; explicit activation required')
    if activate and (live.exists() or live.is_symlink()) and live.resolve() != generated.resolve():
        raise PreflightError(f'refusing unrelated live config destination: {live}')
    retired = []
    if activate:
        for relative in ['hooks.json', 'hooks/atomic-commits.sh', 'hooks/worktree-guard.sh']:
            path = codex / relative
            if path.exists() or path.is_symlink():
                if relative == 'hooks.json' and path.is_file():
                    groups = json.loads(path.read_text()).get('hooks', {}).values()
                    commands = [hook for entries in groups for entry in entries for hook in entry.get('hooks', [])]
                    if commands and all(hook.get('type') == 'command' and 'herdr-agent-state.sh' in hook.get('command', '') for hook in commands):
                        continue
                targets = {directory / relative, home / 'workspace/dotfiles/codex/.codex' / relative}
                if not path.is_symlink() or path.resolve() not in {target.resolve() for target in targets}:
                    raise PreflightError(f'incompatible unmanaged hook source: {path}')
                retired.append(path)
        hooks = codex / 'hooks'
        if hooks.exists() and any(path not in retired for path in hooks.rglob('*') if path.is_file() or path.is_symlink()):
            raise PreflightError(f'incompatible unmanaged hook source: {hooks}')
    base_path = directory / 'config.base.toml'
    if not base_path.is_file():
        raise PreflightError('missing base config')
    base = read(base_path)
    # Absolute machine paths in the base are templates for the target user's HOME.
    def map_paths(value):
        if isinstance(value, str):
            return value.replace('/home/benkim0414/', str(home) + '/', 1) if value.startswith('/home/benkim0414/') else value
        if isinstance(value, list):
            return [map_paths(item) for item in value]
        if isinstance(value, dict):
            return {key: map_paths(item) for key, item in value.items()}
        return value
    base = map_paths(base)
    current = read(live)
    result = merge(base, current)
    for key in ['approval_policy', 'approvals_reviewer', 'sandbox_mode']:
        result[key] = base[key]
    result.pop('auto_review', None)
    result.pop('hooks', None)
    result.setdefault('features', {})['hooks'] = base['features']['hooks']
    result.get('mcp_servers', {}).pop('context-mode', None)
    for key in ['agentmemory', 'compound-engineering-plugin', 'superpowers-marketplace', 'context-mode']:
        result.get('marketplaces', {}).pop(key, None)
    for name in ['agentmemory@agentmemory', 'compound-engineering@compound-engineering-plugin', 'superpowers@superpowers-marketplace']:
        result.get('plugins', {}).pop(name, None)
    text = serialize(result)
    # All refusal/parse/serialization checks above precede filesystem mutation.
    descriptor, temporary = tempfile.mkstemp(prefix='.config-sync-', dir=directory)
    try:
        with os.fdopen(descriptor, 'w') as output:
            output.write(text)
        os.chmod(temporary, 0o600)
        os.replace(temporary, generated)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)
    if activate:
        codex.mkdir(parents=True, exist_ok=True)
        if live.resolve() != generated.resolve():
            live.symlink_to(generated)
        for path in retired:
            path.unlink()
    else:
        print('codex-sync: generated config only; set CODEX_HOME or CODEX_SYNC_LIVE=1 to activate', file=sys.stderr)


if __name__ == '__main__':
    try:
        main()
    except PreflightError as error:
        print('codex-sync: ' + str(error), file=sys.stderr)
        sys.exit(1)
    except (OSError, ValueError, KeyError, TypeError, AttributeError) as error:
        # Do not expose config contents in parser diagnostics.
        print('codex-sync: preflight/generation failed (' + type(error).__name__ + ')', file=sys.stderr)
        sys.exit(1)
