---
- name: Clone dotfiles repo
  git:
    repo: https://github.com/benkim0414/dotfiles
    dest: "{{ ansible_env.HOME }}/workspace/dotfiles"
- name: Install rcm
  become: yes
  apt:
    name: rcm
- name: Copy rcrc to HOME
  copy:
    remote_src: yes
    src: "{{ ansible_env.HOME }}/workspace/dotfiles/tag-pi/rcrc"
    dest: "{{ ansible_env.HOME }}/.rcrc"
- name: Install dotfiles managed by rcm
  shell: rcup -t pi -v
