return {}
-- return {
--   {
--     "vhyrro/luarocks.nvim",
--     priority = 1000,
--     config = true,
--   },
--   {
--     "nvim-neorg/neorg",
--     dependencies = {
--       "nvim-lua/plenary.nvim",
--       "luarocks.nvim",
--     },
--     lalzy = false,
--     version = "*",
--     config = function()
--       require("neorg").setup {
--         load = {
--           ["core.defaults"] = {},
--           ["core.concealer"] = {},
--           ["core.dirman"] = {
--             config = {
--               workspaces = {
--                 notes = "~/notes",
--               },
--             },
--           },
--         },
--       }
--     end,
--   },
-- }
