background {
    monitor =
    color = rgb(111111)
}

input-field {
    monitor =
    size = 280, 56
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.25
    fade_on_empty = false
    placeholder_text = Password
    position = 0, -80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    font_size = 48
    position = 0, 40
    halign = center
    valign = center
}
