source = $HOME/.config/hypr/mocha.conf

$accent = $mauve

background {
    monitor =
    color = $base
}

input-field {
    monitor =
    size = 280, 56
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.25
    outer_color = $accent
    inner_color = $surface0
    font_color = $text
    check_color = $accent
    fail_color = $red
    capslock_color = $yellow
    fade_on_empty = false
    placeholder_text = Password
    position = 0, -80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    color = $text
    font_size = 48
    position = 0, 40
    halign = center
    valign = center
}
