---
- name: Clone fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: "{{ ansible_env.HOME }}/.fzf"
    depth: 1
- name: Run install script
  shell: "{{ ansible_env.HOME }}/.fzf/install"
